In [1]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten
from keras.utils import np_utils
import numpy as np
from matplotlib import pyplot as plt



In [9]:
def is_even_number(x):
    return x % 2 == 0

In [63]:
x_train = list(range(1, 101, 1))
y_train = [0]*len(x_train)
for x in range(len(x_train)):
    if(is_even_number(x_train[x])):
        y_train[x] = 1
    else:
        y_train[x] = 0
print(x_train)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [87]:
X_train = np.array(x_train)
Y_train = np.array(y_train)

In [65]:
# one-hot encoding using keras' numpy-related utilities
n_classes = 10000
print("Shape before one-hot encoding: ", X_train.shape)
X_train = np_utils.to_categorical(X_train, n_classes)
# Y_test = np_utils.to_categorical(y_test, n_classes)
print("Shape after one-hot encoding: ", X_train.shape)


Shape before one-hot encoding:  (100,)
Shape after one-hot encoding:  (100, 10000)


In [88]:
# one-hot encoding using keras' numpy-related utilities
y_classes = 2
print("Shape before one-hot encoding: ", Y_train.shape)
Y_train = np_utils.to_categorical(Y_train, y_classes)
# Y_test = np_utils.to_categorical(y_test, n_classes)
print("Shape after one-hot encoding: ", Y_train.shape)


Shape before one-hot encoding:  (100, 1)
Shape after one-hot encoding:  (100, 2)


In [60]:
X_train

array([[[1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 1., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0.

In [89]:
Y_train

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.

In [99]:
x_train = np.array(X_train).reshape(100, 10000, 1)
y_train = np.array(Y_train).reshape(100, 2)


In [100]:
y_train

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.

In [101]:
# building a linear stack of layers with the sequential model
model = Sequential()
# hidden layer
model.add(Dense(100, input_shape=(10000,), activation='relu'))
# output layer
model.add(Dense(2, activation='softmax'))
# compiling the sequential model
model.compile(loss='categorical_crossentropy',
              metrics=['accuracy'], optimizer='adam')
model.build()
model.summary()

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_34 (Dense)            (None, 100)               1000100   
                                                                 
 dense_35 (Dense)            (None, 2)                 202       
                                                                 
Total params: 1,000,302
Trainable params: 1,000,302
Non-trainable params: 0
_________________________________________________________________


In [102]:
model.fit(x_train, y_train, epochs=100,
          validation_batch_size=0.2, batch_size=3)


Epoch 1/100
34/34 [==============================] - 0s 3ms/step - loss: 0.6942 - accuracy: 0.4500
Epoch 2/100
34/34 [==============================] - 0s 3ms/step - loss: 0.6721 - accuracy: 0.9400
Epoch 3/100
34/34 [==============================] - 0s 3ms/step - loss: 0.6433 - accuracy: 0.9900
Epoch 4/100
34/34 [==============================] - 0s 3ms/step - loss: 0.5932 - accuracy: 1.0000
Epoch 5/100
34/34 [==============================] - 0s 4ms/step - loss: 0.5097 - accuracy: 1.0000
Epoch 6/100
34/34 [==============================] - 0s 3ms/step - loss: 0.3976 - accuracy: 1.0000
Epoch 7/100
34/34 [==============================] - 0s 3ms/step - loss: 0.2788 - accuracy: 1.0000
Epoch 8/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1805 - accuracy: 1.0000
Epoch 9/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1169 - accuracy: 1.0000
Epoch 10/100
34/34 [==============================] - 0s 3ms/step - loss: 0.0796 - accuracy: 1.0000
Epoch 11/

In [107]:
x = [1000]
x = np.array(x)
x = np_utils.to_categorical(x, n_classes)



In [108]:
pred = model.predict(x)
pred

array([[0.51245284, 0.48754716]], dtype=float32)