In [96]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
# keras imports for the dataset and building our neural network
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, LSTM, RepeatVector, TimeDistributed
from keras.utils import np_utils
from matplotlib import pyplot as plt
from attention_decoder import AttentionDecoder

ImportError: cannot import name 'Recurrent' from 'keras.layers.recurrent' (C:\Users\Emmanuel\Documents\Python\Anaconda\Tensorflow Object Detection\TFODCourse\tfod\lib\site-packages\keras-2.6.0-py3.8.egg\keras\layers\recurrent.py)

In [78]:
def generate_sequenceX():
    rand = np.random.randint(0, 1000)
    x = [0]*5
    y = [0]*5
    for i in range(len(x)):
        x[i] = np.random.randint(0, 1000)
        if i == 0:
            y[i] = x[i] * 2
        elif i == 1:
            y[i] = x[i] - 1
        elif i == 2:
            y[i] = (x[i] / 2) +  1
        else:
            y[i] = 0
    return x, y

def generate_all_sequence(count):
    X = [0]*count
    Y = [0] * len(X)
    for i in range(len(X)):
        X[i], Y[i] = generate_sequenceX()
    return X, Y
    

In [79]:
x, y= generate_sequenceX()
print(x, y)

[308, 149, 199, 635, 642] [616, 148, 100.5, 0, 0]


In [80]:
X, Y = generate_all_sequence(10000)

In [142]:
X = list()
Y = list()
X = [x for x in range(5, 301 + 10005, 5)]
Y = [y for y in range(20, 316 + 10005, 5)]

X = np.array(X).reshape(687, 3, 1)
Y = np.array(Y).reshape(687, 3, 1)

In [143]:
print(len(X))
print(len(Y))

687
687


In [138]:
X[: 10]

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [139]:
Y[: 10]

[20, 25, 30, 35, 40, 45, 50, 55, 60, 65]

In [83]:
X = np.array(X)
Y = np.array(Y)

In [84]:
X[:10]
print(X.shape)
X[0].shape

(10000, 5)


(5,)

In [108]:
X = X.reshape(10000, 5, 1)
Y = Y.reshape(10000, 5, 1)

In [158]:
print(X[:10])
X.shape

[[[  5]
  [ 10]
  [ 15]]

 [[ 20]
  [ 25]
  [ 30]]

 [[ 35]
  [ 40]
  [ 45]]

 [[ 50]
  [ 55]
  [ 60]]

 [[ 65]
  [ 70]
  [ 75]]

 [[ 80]
  [ 85]
  [ 90]]

 [[ 95]
  [100]
  [105]]

 [[110]
  [115]
  [120]]

 [[125]
  [130]
  [135]]

 [[140]
  [145]
  [150]]]


(687, 3, 1)

In [144]:
model = Sequential()

# encoder layer
model.add(LSTM(100, activation='relu', input_shape=(3, 1)))

# repeat vector
model.add(RepeatVector(3))

# decoder layer
model.add(LSTM(100, activation='relu', return_sequences=True))

model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')

print(model.summary())




Model: "sequential_26"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_31 (LSTM)               (None, 100)               40800     
_________________________________________________________________
repeat_vector_11 (RepeatVect (None, 3, 100)            0         
_________________________________________________________________
lstm_32 (LSTM)               (None, 3, 100)            80400     
_________________________________________________________________
time_distributed_11 (TimeDis (None, 3, 1)              101       
Total params: 121,301
Trainable params: 121,301
Non-trainable params: 0
_________________________________________________________________
None


In [145]:
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1, batch_size=3)

Epoch 1/1000
183/183 [==============================] - 4s 8ms/step - loss: 3702093.2500 - val_loss: 391395.9062
Epoch 2/1000
183/183 [==============================] - 1s 5ms/step - loss: 24771.0039 - val_loss: 1930.0188
Epoch 3/1000
183/183 [==============================] - 1s 5ms/step - loss: 55.2689 - val_loss: 30.0184
Epoch 4/1000
183/183 [==============================] - 1s 5ms/step - loss: 5.3371 - val_loss: 12.3965
Epoch 5/1000
183/183 [==============================] - 1s 6ms/step - loss: 2.6745 - val_loss: 10.3021
Epoch 6/1000
183/183 [==============================] - 1s 5ms/step - loss: 1.6545 - val_loss: 9.4780
Epoch 7/1000
183/183 [==============================] - 1s 5ms/step - loss: 189.8658 - val_loss: 4.9619
Epoch 8/1000
183/183 [==============================] - 1s 5ms/step - loss: 41.2088 - val_loss: 140.2618
Epoch 9/1000
183/183 [==============================] - 1s 5ms/step - loss: 23.9650 - val_loss: 62.3538
Epoch 10/1000
183/183 [==============================

183/183 [==============================] - 1s 6ms/step - loss: 122.3337 - val_loss: 9.2913
Epoch 78/1000
183/183 [==============================] - 1s 6ms/step - loss: 61.2596 - val_loss: 397.9742
Epoch 79/1000
183/183 [==============================] - 1s 5ms/step - loss: 58.2928 - val_loss: 243.8780
Epoch 80/1000
183/183 [==============================] - 1s 5ms/step - loss: 244.7712 - val_loss: 7.8225
Epoch 81/1000
183/183 [==============================] - 1s 5ms/step - loss: 1207.9702 - val_loss: 25566.9121
Epoch 82/1000
183/183 [==============================] - 1s 5ms/step - loss: 10401.4785 - val_loss: 4401.7612
Epoch 83/1000
183/183 [==============================] - 1s 5ms/step - loss: 98.1503 - val_loss: 11.4339
Epoch 84/1000
183/183 [==============================] - 1s 5ms/step - loss: 2947.6663 - val_loss: 9.4457
Epoch 85/1000
183/183 [==============================] - 1s 6ms/step - loss: 1286.7859 - val_loss: 253.4390
Epoch 86/1000
183/183 [==============================

183/183 [==============================] - 1s 5ms/step - loss: 1948.5043 - val_loss: 83.8822
Epoch 154/1000
183/183 [==============================] - 1s 5ms/step - loss: 35.9513 - val_loss: 230.1019
Epoch 155/1000
183/183 [==============================] - 1s 6ms/step - loss: 10.3938 - val_loss: 10.3958
Epoch 156/1000
183/183 [==============================] - 1s 6ms/step - loss: 9.2918 - val_loss: 17.7172
Epoch 157/1000
183/183 [==============================] - 1s 6ms/step - loss: 43.2321 - val_loss: 155.7635
Epoch 158/1000
183/183 [==============================] - 1s 6ms/step - loss: 23.3105 - val_loss: 32.5287
Epoch 159/1000
183/183 [==============================] - 1s 7ms/step - loss: 49.2787 - val_loss: 57.1958
Epoch 160/1000
183/183 [==============================] - 1s 6ms/step - loss: 5660.0376 - val_loss: 140103.5312
Epoch 161/1000
183/183 [==============================] - 1s 8ms/step - loss: 1704.3188 - val_loss: 5.2821
Epoch 162/1000
183/183 [===========================

183/183 [==============================] - 2s 11ms/step - loss: 15.3554 - val_loss: 12.6502
Epoch 230/1000
183/183 [==============================] - 3s 15ms/step - loss: 26.2260 - val_loss: 30.9703
Epoch 231/1000
183/183 [==============================] - 3s 14ms/step - loss: 1965.8727 - val_loss: 366.5520
Epoch 232/1000
183/183 [==============================] - 2s 13ms/step - loss: 42.3391 - val_loss: 178.2169
Epoch 233/1000
183/183 [==============================] - 2s 12ms/step - loss: 33.5714 - val_loss: 4.6230
Epoch 234/1000
183/183 [==============================] - 2s 13ms/step - loss: 7.0466 - val_loss: 27.5278
Epoch 235/1000
183/183 [==============================] - 2s 11ms/step - loss: 69.9367 - val_loss: 31.7441
Epoch 236/1000
183/183 [==============================] - 2s 11ms/step - loss: 5727.3921 - val_loss: 55162.5156
Epoch 237/1000
183/183 [==============================] - 2s 12ms/step - loss: 1787.7424 - val_loss: 5.1730
Epoch 238/1000
183/183 [====================

Epoch 306/1000
183/183 [==============================] - 2s 10ms/step - loss: 4.0079 - val_loss: 8.9192
Epoch 307/1000
183/183 [==============================] - 2s 10ms/step - loss: 4.0160 - val_loss: 8.0642
Epoch 308/1000
183/183 [==============================] - 2s 10ms/step - loss: 3.9902 - val_loss: 9.0922
Epoch 309/1000
183/183 [==============================] - 2s 11ms/step - loss: 3.9838 - val_loss: 6.2405
Epoch 310/1000
183/183 [==============================] - 2s 10ms/step - loss: 3.9723 - val_loss: 6.0985
Epoch 311/1000
183/183 [==============================] - 2s 10ms/step - loss: 3.9640 - val_loss: 6.5566
Epoch 312/1000
183/183 [==============================] - 2s 10ms/step - loss: 3.9582 - val_loss: 7.3887
Epoch 313/1000
183/183 [==============================] - 2s 10ms/step - loss: 2061.5151 - val_loss: 8760.2646
Epoch 314/1000
183/183 [==============================] - 2s 10ms/step - loss: 108.3226 - val_loss: 11.8722
Epoch 315/1000
183/183 [======================

183/183 [==============================] - 2s 10ms/step - loss: 3.9356 - val_loss: 6.7119
Epoch 384/1000
183/183 [==============================] - 2s 10ms/step - loss: 3.9926 - val_loss: 5.2365
Epoch 385/1000
183/183 [==============================] - 2s 10ms/step - loss: 3.8724 - val_loss: 11.3092
Epoch 386/1000
183/183 [==============================] - 2s 13ms/step - loss: 4.0344 - val_loss: 6.5666
Epoch 387/1000
183/183 [==============================] - 2s 11ms/step - loss: 3.9573 - val_loss: 14.2138
Epoch 388/1000
183/183 [==============================] - 2s 10ms/step - loss: 4955.0312 - val_loss: 356384.8125
Epoch 389/1000
183/183 [==============================] - 2s 10ms/step - loss: 17088.9922 - val_loss: 223736.7812
Epoch 390/1000
183/183 [==============================] - 2s 11ms/step - loss: 3012.3835 - val_loss: 7.5892
Epoch 391/1000
183/183 [==============================] - 2s 12ms/step - loss: 140193.0938 - val_loss: 20298.2500
Epoch 392/1000
183/183 [===============

Epoch 460/1000
183/183 [==============================] - 2s 12ms/step - loss: 19.3249 - val_loss: 8.5701
Epoch 461/1000
183/183 [==============================] - 2s 13ms/step - loss: 402.7831 - val_loss: 2.8064
Epoch 462/1000
183/183 [==============================] - 2s 12ms/step - loss: 93.0896 - val_loss: 4.3296
Epoch 463/1000
183/183 [==============================] - 3s 14ms/step - loss: 1173.4421 - val_loss: 3.8169
Epoch 464/1000
183/183 [==============================] - 2s 13ms/step - loss: 5.1051 - val_loss: 4.1711
Epoch 465/1000
183/183 [==============================] - 2s 9ms/step - loss: 3.3668 - val_loss: 12.8864
Epoch 466/1000
183/183 [==============================] - 1s 8ms/step - loss: 7.2540 - val_loss: 13.7476
Epoch 467/1000
183/183 [==============================] - 1s 7ms/step - loss: 14.0661 - val_loss: 27.9377
Epoch 468/1000
183/183 [==============================] - 1s 7ms/step - loss: 6010.8540 - val_loss: 6730.9985
Epoch 469/1000
183/183 [==================

Epoch 537/1000
183/183 [==============================] - 1s 6ms/step - loss: 2.0167 - val_loss: 4.2386
Epoch 538/1000
183/183 [==============================] - 1s 6ms/step - loss: 1.9167 - val_loss: 2.4304
Epoch 539/1000
183/183 [==============================] - 1s 6ms/step - loss: 3594.6555 - val_loss: 15.5286
Epoch 540/1000
183/183 [==============================] - 1s 5ms/step - loss: 10.2824 - val_loss: 5.3952
Epoch 541/1000
183/183 [==============================] - 1s 6ms/step - loss: 2709.5967 - val_loss: 88.6773
Epoch 542/1000
183/183 [==============================] - 1s 5ms/step - loss: 4.8701 - val_loss: 11.3159
Epoch 543/1000
183/183 [==============================] - 1s 5ms/step - loss: 3.5204 - val_loss: 5.4665
Epoch 544/1000
183/183 [==============================] - 1s 5ms/step - loss: 2.8701 - val_loss: 6.1956
Epoch 545/1000
183/183 [==============================] - 1s 5ms/step - loss: 2307.5527 - val_loss: 27.9988
Epoch 546/1000
183/183 [==========================

183/183 [==============================] - 1s 5ms/step - loss: 17.5292 - val_loss: 1.7655
Epoch 615/1000
183/183 [==============================] - 1s 5ms/step - loss: 3.9280 - val_loss: 8.5594
Epoch 616/1000
183/183 [==============================] - 1s 5ms/step - loss: 9.9207 - val_loss: 57.7678
Epoch 617/1000
183/183 [==============================] - 1s 5ms/step - loss: 12.3972 - val_loss: 8.5214
Epoch 618/1000
183/183 [==============================] - 1s 6ms/step - loss: 11.6344 - val_loss: 1.0330
Epoch 619/1000
183/183 [==============================] - 1s 5ms/step - loss: 138.0742 - val_loss: 821.7151
Epoch 620/1000
183/183 [==============================] - 1s 5ms/step - loss: 1776.5117 - val_loss: 17.9917
Epoch 621/1000
183/183 [==============================] - 1s 5ms/step - loss: 4.2081 - val_loss: 12.3006
Epoch 622/1000
183/183 [==============================] - 1s 5ms/step - loss: 4.2457 - val_loss: 8.5060
Epoch 623/1000
183/183 [==============================] - 1s 5ms/s

183/183 [==============================] - 1s 6ms/step - loss: 1.7783 - val_loss: 4.6445
Epoch 692/1000
183/183 [==============================] - 1s 5ms/step - loss: 1.7022 - val_loss: 7.9538
Epoch 693/1000
183/183 [==============================] - 1s 5ms/step - loss: 1.8053 - val_loss: 1.5761
Epoch 694/1000
183/183 [==============================] - 1s 5ms/step - loss: 2.1704 - val_loss: 2.4691
Epoch 695/1000
183/183 [==============================] - 1s 5ms/step - loss: 1.7233 - val_loss: 5.2563
Epoch 696/1000
183/183 [==============================] - 1s 5ms/step - loss: 1.7445 - val_loss: 4.2358
Epoch 697/1000
183/183 [==============================] - 1s 6ms/step - loss: 1.7801 - val_loss: 2.0462
Epoch 698/1000
183/183 [==============================] - 1s 6ms/step - loss: 2.5776 - val_loss: 6.8285
Epoch 699/1000
183/183 [==============================] - 1s 7ms/step - loss: 3.3449 - val_loss: 2.3727
Epoch 700/1000
183/183 [==============================] - 2s 8ms/step - loss: 2

Epoch 769/1000
183/183 [==============================] - 1s 6ms/step - loss: 1.8269 - val_loss: 3.7458
Epoch 770/1000
183/183 [==============================] - 1s 7ms/step - loss: 1.7789 - val_loss: 2.3289
Epoch 771/1000
183/183 [==============================] - 2s 10ms/step - loss: 2.9485 - val_loss: 4.6031
Epoch 772/1000
183/183 [==============================] - 2s 11ms/step - loss: 1.9387 - val_loss: 3.0777
Epoch 773/1000
183/183 [==============================] - 2s 14ms/step - loss: 1.5962 - val_loss: 5.8524
Epoch 774/1000
183/183 [==============================] - 2s 11ms/step - loss: 2.1216 - val_loss: 3.1837
Epoch 775/1000
183/183 [==============================] - 2s 13ms/step - loss: 650.4043 - val_loss: 7271.1489
Epoch 776/1000
183/183 [==============================] - 3s 15ms/step - loss: 64.9520 - val_loss: 7.5331
Epoch 777/1000
183/183 [==============================] - 2s 13ms/step - loss: 1.9177 - val_loss: 3.1920
Epoch 778/1000
183/183 [===========================

183/183 [==============================] - 2s 12ms/step - loss: 4.4633 - val_loss: 4.7479 ETA: 0s - loss: 
Epoch 847/1000
183/183 [==============================] - 2s 11ms/step - loss: 4.5206 - val_loss: 4.7246
Epoch 848/1000
183/183 [==============================] - 2s 11ms/step - loss: 4.4749 - val_loss: 4.9749
Epoch 849/1000
183/183 [==============================] - 2s 12ms/step - loss: 4.4590 - val_loss: 4.7331
Epoch 850/1000
183/183 [==============================] - 2s 13ms/step - loss: 4.6232 - val_loss: 4.2761
Epoch 851/1000
183/183 [==============================] - 2s 10ms/step - loss: 10.7590 - val_loss: 27.0217
Epoch 852/1000
183/183 [==============================] - 2s 10ms/step - loss: 18.1654 - val_loss: 4.4728
Epoch 853/1000
183/183 [==============================] - 2s 10ms/step - loss: 57.0240 - val_loss: 5.5737
Epoch 854/1000
183/183 [==============================] - 2s 11ms/step - loss: 4.5543 - val_loss: 4.4449
Epoch 855/1000
183/183 [=========================

183/183 [==============================] - 2s 12ms/step - loss: 4.3253 - val_loss: 4.1826
Epoch 924/1000
183/183 [==============================] - 2s 10ms/step - loss: 5.0550 - val_loss: 21.8030
Epoch 925/1000
183/183 [==============================] - 2s 10ms/step - loss: 8.0720 - val_loss: 21.2371
Epoch 926/1000
183/183 [==============================] - 2s 11ms/step - loss: 370.2991 - val_loss: 9059.1621
Epoch 927/1000
183/183 [==============================] - 2s 11ms/step - loss: 105.7396 - val_loss: 5.5234
Epoch 928/1000
183/183 [==============================] - 2s 12ms/step - loss: 4.2660 - val_loss: 4.6918
Epoch 929/1000
183/183 [==============================] - 3s 14ms/step - loss: 7.3606 - val_loss: 32.0695
Epoch 930/1000
183/183 [==============================] - 2s 11ms/step - loss: 1650.2301 - val_loss: 19.9838
Epoch 931/1000
183/183 [==============================] - 2s 10ms/step - loss: 20.8722 - val_loss: 4.7773
Epoch 932/1000
183/183 [==============================]

183/183 [==============================] - 2s 11ms/step - loss: 681.2175 - val_loss: 7.2283


In [156]:
x_test = np.array([100, 105, 110]).reshape(1, 3, 1)
x_test

array([[[100],
        [105],
        [110]]])

In [157]:
pred = model.predict(x_test)
np.around(pred[0])

array([[115.],
       [122.],
       [122.]], dtype=float32)